services:
  - type: web
    name: social-media-downloader-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DECODO_PROXY_ENABLED
        value: "true"
      - key: DECODO_HOST
        value: gate.decodo.com
      - key: DECODO_PORT
        value: "7000"
      - key: DECODO_COUNTRY
        value: in
      - key: MAX_CONCURRENT_JOBS
        value: "1"
      - key: YTDLP_RETRIES
        value: "3"
      - key: YTDLP_FRAGMENT_RETRIES
        value: "3"
      - key: UVICORN_LIMIT_CONCURRENCY
        value: "16"
      - key: DECODO_USERNAME
        sync: false
      - key: DECODO_PASSWORD
        sync: false
